version: '3'
services:
  server:
    container_name: "dndbot-server"
    image: dndbot-server:latest
    env_file: ".env"
    deploy: 
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
    ports:
      - "${SERVERPORT}:5000"
  bot:
    container_name: "dndbot-bot"
    image: dndbot-bot:latest
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any
        delay: 10s 
        window: 120s
  client:
    container_name: "dndbot-client"
    image: dndbot-client:latest
    env_file: ".env"
    deploy:
      restart_policy:
        condition: any
        delay: 10s 
        window: 120s
    ports:
      - "${CLIENTPORT}:80"