version: '3'
services:
  server:
    container_name: dndmusicbot
    image: ghcr.io/jordyjordy/dndmusicbot:latest
    env_file: ".env"
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 10s 
        window: 60s
        max_attempts: 10
    ports:
      - "${SERVERPORT}:5000"      
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 dndmusicbot