version: '3'
services:
  server:
    container_name: "dndbot-server"
    image: dndbot-server
    env_file: ".env"
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 10s 
        window: 60s
        max_attempts: 10
    ports:
      - "${SERVERPORT}:5000"
    labels:
      - "com.centurylinklabs.watchtower.scope=dndbot"
  bot:
    container_name: "dndbot-newbot-duplicate"
    image: dndbot-newbot
    env_file: ".env.duplicate"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s 
        window: 60s
        max_attempts: 10
      labels:
        - "com.centurylinklabs.watchtower.scope=dndbot"
  newbot:
    container_name: "dndbot-newbot"
    image: dndbot-newbot
    env_file: ".env"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s 
        window: 60s
        max_attempts: 10
      labels:
        - "com.centurylinklabs.watchtower.scope=dndbot"
  client:
    container_name: "dndbot-client"
    image: dndbot-client
    env_file: ".env"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s 
        window: 60s
        max_attempts: 10
    ports:
      - "${CLIENTPORT}:80"
    labels:
      - "com.centurylinklabs.watchtower.scope=dndbot"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --scope dndbot
    labels:
      - "com.centurylinklabs.watchtower.scope=dndbot"