name: test validation
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: test/eslint
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm run bootstrap
      - run: npm run test
      - run: npm run lint