name: test validation
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test/eslint
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: echo "@jordyjordy:registry=https://registry.npmjs.org/:always-auth=true" > .npmrc
      - run: npm run bootstrap
      - run: npm run test
      - run: npm run lint